<?xml version="1.0"?>
<robot xmlns:xacro="http://wiki.ros.org/xacro">
  <xacro:macro name="boss_male" params="name parent_link model *origin">
    <xacro:property name="mesh_scale" value="0.001 0.001 0.001"/>
    <xacro:if value="${model == 'UNC_58'}">
        <xacro:property name="mesh_x" value="0.030"/>
        <xacro:property name="mesh_y" value="0.030"/>
        <xacro:property name="mesh_z" value="0.021"/>
        <xacro:property name="mesh_filename" value="package://clearpath_mounts_description/meshes/boss_male/137-0040-00.stl"/>
    </xacro:if>
    <link name="${name}_link">
      <visual>
        <geometry>
          <mesh filename="${mesh_filename}" scale="${mesh_scale}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 ${pi/2}" />
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${mesh_x/2.0}" length="${mesh_z}" />
        </geometry>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      </collision>
    </link>

    <link name="${name}_mount" />

    <joint name="${name}_joint" type="fixed">
      <parent link="${parent_link}" />
      <child link="${name}_link" />
      <xacro:insert_block name="origin" />
    </joint>

    <joint name="${name}_mount_joint" type="fixed">
      <child link="${name}_mount" />
      <parent link="${name}_link" />
      <origin xyz="0 0 ${mesh_z}"/>
    </joint>

  </xacro:macro>
</robot>