twist_server_node:
  ros__parameters:
    use_sim_time: False
    link_name: base_link
    robot: max
    linear_scale: 1.0
    max_positive_linear_velocity: 3.5
    max_negative_linear_velocity: -3.5